import Head from "next/head";
import Image from "next/image";

export default function Home() {

  const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=imperial&lat={lat}&lon={lon}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center text-blue-600 font-bold justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
      <Head>
        <title>Weather - Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello</h1>
    </div>
  );
}
